### ISSUE TITLE
Dropwizard .9

### ISSUE THREAD

**Issue by esnellman** [benjamin-bader/droptools#17]
Anyone already working toward supporting .9?  I might fork and work it.

Exception in thread "main" java.lang.NoSuchMethodError: com.bendb.dropwizard.jooq.JooqBundle.getDataSourceFactory(Lio/dropwizard/Configuration;)Lio/dropwizard/db/DataSourceFactory;
	at com.bendb.dropwizard.jooq.JooqBundle.run(JooqBundle.java:33)
	at com.bendb.dropwizard.jooq.JooqBundle.run(JooqBundle.java:14)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)

https://github.com/dropwizard/dropwizard/blob/release/0.9.x/dropwizard-db/src/main/java/io/dropwizard/db/DatabaseConfiguration.java
change to PooledDataSourceFactory from DataSourceFactory

**Comment by benjamin-bader** [comment]
Hi, I haven't been doing any Dropwizard work for a while, so this project has definitely fallen behind.  I'd be happy to take any pull requests you'd care to make; otherwise I'll check it out in my spare time at some point soon.

**Comment by esnellman** [comment]
I added a cast, it compiles and turns on but I still need to test queries.

**Comment by benjamin-bader** [comment]
It ought to work - that's the only implementation of the new interface in the project.  I'm seeing about adding the missing `getUrl()` call to the interface, but a cast should work for just about everybody regardless.
