### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()

### ISSUE THREAD

**Issue by francjohny** [benjamin-bader/droptools#44]
### What happened?
```
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
	at com.bendb.dropwizard.redis.JedisFactory.getHost(JedisFactory.java:108)
	at com.bendb.dropwizard.redis.JedisFactory.build(JedisFactory.java:168)
	at com.bendb.dropwizard.redis.JedisBundle.run(JedisBundle.java:25)
	at com.bendb.dropwizard.redis.JedisBundle.run(JedisBundle.java:11)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:74)
	at io.dropwizard.Application.run(Application.java:93)
```
#### `getHostText()` seems deprecated in guava 22.0
```
public String getHost() {
        return endpoint.getHostText();
    }
```

### How to reproduce this issue?
Try to compile the project

### Possible fix - replacing with getHost()
```
/**
   * Returns the portion of this {@code HostAndPort} instance that should represent the hostname or
   * IPv4/IPv6 literal.
   *
   * <p>A successful parse does not imply any degree of sanity in this field. For additional
   * validation, see the {@link HostSpecifier} class.
   *
   * @since 20.0 (since 10.0 as {@code getHostText})
   */
  public String getHost() {
    return host;
  }
```
Thanks!

**Comment by francjohny** [comment]
Just realised the issue is with an old dropwizard-redis dependency in the [README.md](https://github.com/benjamin-bader/droptools/blob/master/dropwizard-redis/README.md)

issue is fixed with the latest dependency - [1.2.0-0](https://mvnrepository.com/artifact/com.bendb.dropwizard/dropwizard-redis/1.2.0-0)

**Comment by francjohny** [comment]
Added a fix here: https://github.com/benjamin-bader/droptools/pull/45

**Comment by benjamin-bader** [comment]
Thanks for the readme update - is everything good on your end now?

**Comment by francjohny** [comment]
Absolutely. Thanks a lot @benjamin-bader!
