### ISSUE TITLE
dropwizard-jooq: ClassNotFoundException: com.sun.jersey.spi.inject.InjectableProvider

### ISSUE THREAD

**Issue by steveme** [benjamin-bader/droptools#5]
Hi,

I'm not having any luck getting dropwizard-jooq working in a really simple example that is 99% copied from the https://github.com/benjamin-bader/droptools/tree/master/droptools-example.

My dependencies are:
```
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4-1201-jdbc41</version>
        </dependency>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>0.8.0-rc1</version>
        </dependency>
        <dependency>
            <groupId>com.bendb.dropwizard</groupId>
            <artifactId>dropwizard-jooq</artifactId>
            <version>0.7.1-5</version>
        </dependency>
```
And I see this exception at startup, even with no registered resources.

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/sun/jersey/spi/inject/InjectableProvider
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.bendb.dropwizard.jooq.JooqBundle.run(JooqBundle.java:28)
        at com.bendb.dropwizard.jooq.JooqBundle.run(JooqBundle.java:12)
        at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:176)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:73)
        at uk.co.eventgenius.api.ApiApplication.main(ApiApplication.java:23)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.spi.inject.InjectableProvider
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 25 more
```

It looks like something's looking for jersey-core but I tried including that to no avail. Have tried cloning droptools-example and while I didn't get it to start up fully (as I didn't setup the db), it loaded farther than i've managed so far separately, and I can't see it using InjectableProvider or having access to it from it's dependencies.

Am I doing something daft?

Thanks,

Steve

**Comment by benjamin-bader** [comment]
Hi Steve, it looks like you have a version mismatch.  `0.7.1-5` is only compatible with Dropwizard version 0.7.1 (it's actually compatible with 0.7.X, generally, but that's the guarantee implied by the version number).

The class definition that's missing is part of the old Jersey 1.X dependency injection framework.  Jersey 2, adopted in DW 0.8, uses an entirely different framework called HK2.  I haven't touched this much lately, but I did push a snapshot build targeting `0.8.0-rc1` a while back (see issue #4).  You'll have better luck using this version.

I need to do a bit of work to keep this project up-to-date - thanks for reminding me!

**Comment by benjamin-bader** [comment]
This ought to be documented somewhere that isn't Google Groups, but the weird versioning seen here is Dropwizard's third-party module policy: https://groups.google.com/forum/#!msg/dropwizard-dev/nY23U4996_k/rKP_e05sIRAJ

**Comment by steveme** [comment]
Thanks!
